#!/bin/python3

def manifestRdf_func(directory):
    print('\033[33m'+'Generating manifest.rdf'+'\033[0m')
    manifestRdf = open(directory+'/.mde2pdfTmp/odt-u/manifest.rdf', 'a')
    manifestRdf.write('<?xml version="1.0" encoding="utf-8"?>\n')
    manifestRdf.write('<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n')
    manifestRdf.write('  <rdf:Description rdf:about="styles.xml">\n')
    manifestRdf.write('    <rdf:type rdf:resource="http://docs.oasis-open.org/ns/office/1.2/meta/odf#StylesFile"/>\n')
    manifestRdf.write('  </rdf:Description>\n')
    manifestRdf.write('  <rdf:Description rdf:about="">\n')
    manifestRdf.write('    <ns0:hasPart xmlns:ns0="http://docs.oasis-open.org/ns/office/1.2/meta/pkg#" rdf:resource="styles.xml"/>\n')
    manifestRdf.write('  </rdf:Description>\n')
    manifestRdf.write('  <rdf:Description rdf:about="content.xml">\n')
    manifestRdf.write('    <rdf:type rdf:resource="http://docs.oasis-open.org/ns/office/1.2/meta/odf#ContentFile"/>\n')
    manifestRdf.write('  </rdf:Description>\n')
    manifestRdf.write('  <rdf:Description rdf:about="">\n')
    manifestRdf.write('    <ns0:hasPart xmlns:ns0="http://docs.oasis-open.org/ns/office/1.2/meta/pkg#" rdf:resource="content.xml"/>\n')
    manifestRdf.write('  </rdf:Description>\n')
    manifestRdf.write('  <rdf:Description rdf:about="">\n')
    manifestRdf.write('    <rdf:type rdf:resource="http://docs.oasis-open.org/ns/office/1.2/meta/pkg#Document"/>\n')
    manifestRdf.write('  </rdf:Description>\n')
    manifestRdf.write('</rdf:RDF>')
    manifestRdf.close()